before_script:
  - apt update -qy
  - apt install -y python3.7 python3-pip
  - apt install python3-tk
  - python3 -m pip install --upgrade pip
  - python3 -m pip install .

tests:
  stage: test
  script:
    - python3 -m pip install pytest pytest-cov coverage
    - cd tests
    - pytest --basetemp=tmp_dir --cov=excels2vensim *.py
    - coverage xml
  artifacts:
    reports:
      cobertura: tests/coverage.xml

docs:
  stage: test
  script:
    - python3 -m pip install sphinx sphinx_rtd_theme mock
    - cd docs
    - make html

pypi:
  stage: deploy
  only:
    - tags
  script:
    - python3 -m pip install setuptools wheel twine
    - python3 setup.py sdist bdist_wheel
    - TWINE_USERNAME=__token__ TWINE_PASSWORD=$PYPI_TOKEN python3 -m twine upload --verbose dist/*
